/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLMoviequotes_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   moviequotes/v1
// Description:
//   Movie Quotes API

#import "GTLMoviequotesConstants.m"

#import "GTLMoviequotesMovieQuote.m"
#import "GTLMoviequotesMovieQuoteCollection.m"

#import "GTLQueryMoviequotes.m"
#import "GTLServiceMoviequotes.m"
