/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-09-16 16:01:30 UTC)
 * on 2013-09-24 at 15:19:58 UTC 
 * Modify at your own risk.
 */

package com.appspot.fisherds_movie_quotes.moviequotes.model;

/**
 * Model definition for MovieQuote.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the moviequotes. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MovieQuote extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("last_touch_date_time")
  private java.lang.String lastTouchDateTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("movie_title")
  private java.lang.String movieTitle;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String quote;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public MovieQuote setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLastTouchDateTime() {
    return lastTouchDateTime;
  }

  /**
   * @param lastTouchDateTime lastTouchDateTime or {@code null} for none
   */
  public MovieQuote setLastTouchDateTime(java.lang.String lastTouchDateTime) {
    this.lastTouchDateTime = lastTouchDateTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMovieTitle() {
    return movieTitle;
  }

  /**
   * @param movieTitle movieTitle or {@code null} for none
   */
  public MovieQuote setMovieTitle(java.lang.String movieTitle) {
    this.movieTitle = movieTitle;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getQuote() {
    return quote;
  }

  /**
   * @param quote quote or {@code null} for none
   */
  public MovieQuote setQuote(java.lang.String quote) {
    this.quote = quote;
    return this;
  }

  @Override
  public MovieQuote set(String fieldName, Object value) {
    return (MovieQuote) super.set(fieldName, value);
  }

  @Override
  public MovieQuote clone() {
    return (MovieQuote) super.clone();
  }

}
