/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLQueryMoviequotes.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   moviequotes/v1
// Description:
//   Movie Quotes API
// Classes:
//   GTLQueryMoviequotes (3 custom class methods, 5 custom properties)

#import "GTLQueryMoviequotes.h"

#import "GTLMoviequotesMovieQuote.h"
#import "GTLMoviequotesMovieQuoteCollection.h"

@implementation GTLQueryMoviequotes

@dynamic fields, identifier, limit, order, pageToken;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

#pragma mark -
#pragma mark "quote" methods
// These create a GTLQueryMoviequotes object.

+ (id)queryForQuoteDeleteWithIdentifier:(long long)identifier {
  NSString *methodName = @"moviequotes.quote.delete";
  GTLQueryMoviequotes *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.expectedObjectClass = [GTLMoviequotesMovieQuote class];
  return query;
}

+ (id)queryForQuoteInsertWithObject:(GTLMoviequotesMovieQuote *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"moviequotes.quote.insert";
  GTLQueryMoviequotes *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLMoviequotesMovieQuote class];
  return query;
}

#pragma mark -
#pragma mark "quotes" methods
// These create a GTLQueryMoviequotes object.

+ (id)queryForQuotesList {
  NSString *methodName = @"moviequotes.quotes.list";
  GTLQueryMoviequotes *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLMoviequotesMovieQuoteCollection class];
  return query;
}

@end
